# System
alias refresh='source ~/.bashrc'
alias cue='code ~/.bash_aliases'
alias machine='cd ~/machine-setup'
alias code_machine='code ~/machine-setup'
# File system
alias exp='xdg-open .'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../..'
alias .....='cd ../../../../..'
alias ......='cd ../../../../../..'
alias .......='cd ../../../../../../..'
# Git
alias gb='git branch'
alias gd='git diff'
alias gs='git status'
alias gp='git push'
alias gpf='git push -f'
alias gco='git checkout master'
alias gcom='git checkout main'
alias gpom='git pull origin main'
alias gal='git add --all'
alias grbi='git rebase -i main'
alias gcr='git rebase --continue'
alias cane='git commit --amend --no-edit'
# Tmux
alias tmux_refresh='tmux source-file ~/.tmux.conf'
# Glydways
alias code_gld='code ~/glyd'
alias gld='cd ~/glyd'
alias gldmake='~/glyd/make.sh'
alias xsens='cd ~/glyd/third_party/xsens_mt'
alias ark='cd ~/glyd/third_party/ark'
alias ncom='cd ~/glyd/third_party/oxts_ncom_sdk'
alias oxts='cd ~/glyd/glyd/onboard/imu/oxts'
alias xsens='cd ~/glyd/glyd/onboard/imu/xsens'
alias at128='cd ~/glyd/glyd/onboard/lidar/hesai/at128'
alias conti='cd ~/glyd/glyd/onboard/radar/continental/ars540'
alias bench='cd ~/glyd/glyd/onboard/pipelines/bench_data_collection'
# Docker
alias docker_enable='systemctl --user enable docker-desktop'
alias docker_start='systemctl --user start docker-desktop'
alias docker_stop='systemctl --user stop docker-desktop'
